version: '3.9'

networks:
  mercado-network:

services:
  banco-mercado:
    image: postgres:14-alpine
    container_name: "banco-mercado"
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD=""		
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mercado_db
    ports:
      - "5432:5432"
    networks:
      - mercado-network

  mongodb-pedido:
    image: "mongo"
    container_name: "mongodb-pedido"
    ports:
      - "27017:27017"
    networks:
      - mercado-network
  
  gateway:
    container_name: "gateway"
    build: ./gateway
    ports: 
      - "8080:8080"
    environment:
      MS_CLIENTE_URI: ms-cliente
      MS_PRODUTOS_URI: ms-produto
      MS_PEDIDOS_URI: ms-pedidos
      MS_LOGISTICA_ENTREGA_URI: ms-logistica-entrega
    networks:
      - mercado-network

  ms-cliente:
    container_name: "ms-cliente"
    build: ./ms-cliente
    ports:
      - "8081:8081"
    depends_on:
      - banco-mercado
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://banco-mercado:5432/mercado_db
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - mercado-network

  ms-produto:
    container_name: "ms-produto"
    build: ./ms-produtos
    ports: 
      - "8082:8082"
    depends_on:
      - banco-mercado
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://banco-mercado:5432/mercado_db
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - mercado-network

  ms-pedidos:
    container_name: "ms-pedidos"
    build: ./ms-pedidos
    ports:
      - "8083:8083"
    depends_on:
      - mongodb-pedido
    environment:
      MONGO_URI: mongodb://mongodb-pedido:27017/restaurante?authSource=admin
    networks:
      - mercado-network

  ms-logistica-entrega:
    container_name: "ms-logistica-entrega"
    build:
      context: ./ms-logistica-entrega
    ports:
      - "8084:8084"
      - "587:587"
    depends_on:
      - banco-mercado
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://banco-mercado:5432/mercado_db
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      MS_PEDIDOS_URI: ms-pedidos
      MS_CLIENTE_URI: ms-cliente
    networks:
      - mercado-network