FROM amazoncorretto:17-alpine
WORKDIR /app

COPY ms-cliente/build/libs/*.jar ms-cliente.jar
ENTRYPOINT ["java", "-jar", "ms-cliente.jar"]

COPY ms-produtos/build/libs/*.jar ms-produtos.jar
ENTRYPOINT ["java", "-jar", "ms-produtos.jar"]

COPY ms-pedidos/build/libs/*.jar ms-pedidos.jar
ENTRYPOINT ["java", "-jar", "ms-pedidos.jar"]

COPY ms-logistica-entrega/build/libs/*.jar ms-logistica-entrega.jar
ENTRYPOINT ["java", "-jar", "ms-logistica-entrega.jar"]